set_property IOSTANDARD LVCMOS33 [get_ports rx_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_on]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports tx_out]

set_property PACKAGE_PIN N5 [get_ports rx_in]
set_property PACKAGE_PIN P17 [get_ports sys_clk_in]
set_property PACKAGE_PIN U4 [get_ports rst_on]
set_property PACKAGE_PIN T4 [get_ports tx_out]

set_property PACKAGE_PIN H4 [get_ports front_detector_out]
set_property PACKAGE_PIN J3 [get_ports back_detector_out]
set_property PACKAGE_PIN J2 [get_ports left_detector_out]
set_property PACKAGE_PIN K2 [get_ports right_detector_out]
set_property PACKAGE_PIN P4 [get_ports move_backward_in]
set_property PACKAGE_PIN P5 [get_ports move_forward_in]
set_property PACKAGE_PIN P3 [get_ports turn_left_in]
set_property PACKAGE_PIN P2 [get_ports turn_right_in]
set_property IOSTANDARD LVCMOS33 [get_ports move_backward_in]
set_property IOSTANDARD LVCMOS33 [get_ports move_forward_in]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left_in]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right_in]
set_property IOSTANDARD LVCMOS33 [get_ports back_detector_out]
set_property IOSTANDARD LVCMOS33 [get_ports front_detector_out]
set_property IOSTANDARD LVCMOS33 [get_ports left_detector_out]
set_property IOSTANDARD LVCMOS33 [get_ports right_detector_out]

set_property PACKAGE_PIN N4 [get_ports clutch_in]
set_property PACKAGE_PIN R1 [get_ports brake_in]
set_property IOSTANDARD LVCMOS33 [get_ports clutch_in]
set_property IOSTANDARD LVCMOS33 [get_ports brake_in]


set_property PACKAGE_PIN V1 [get_ports turn_l]
set_property PACKAGE_PIN R11 [get_ports turn_r]
set_property PACKAGE_PIN R17 [get_ports rst_off]
set_property IOSTANDARD LVCMOS33 [get_ports turn_l]
set_property IOSTANDARD LVCMOS33 [get_ports turn_r]
set_property IOSTANDARD LVCMOS33 [get_ports rst_off]

set_property PACKAGE_PIN F6 [get_ports on]
set_property IOSTANDARD LVCMOS33 [get_ports on]

set_property PACKAGE_PIN R2 [get_ports place_barrier_in]
set_property IOSTANDARD LVCMOS33 [get_ports place_barrier_in]

set_property PACKAGE_PIN M4 [get_ports destroy_barrier_in]
set_property IOSTANDARD LVCMOS33 [get_ports destroy_barrier_in]

set_property PACKAGE_PIN F1 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property PACKAGE_PIN E1 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property PACKAGE_PIN G6 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]

set_property PACKAGE_PIN D4 [get_ports {mile_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[7]}]
set_property PACKAGE_PIN E3 [get_ports {mile_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[6]}]
set_property PACKAGE_PIN D3 [get_ports {mile_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[5]}]
set_property PACKAGE_PIN F4 [get_ports {mile_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[4]}]
set_property PACKAGE_PIN F3 [get_ports {mile_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[3]}]
set_property PACKAGE_PIN E2 [get_ports {mile_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[2]}]
set_property PACKAGE_PIN D2 [get_ports {mile_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[1]}]
set_property PACKAGE_PIN H2 [get_ports {mile_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mile_seg[0]}]

set_property PACKAGE_PIN R15 [get_ports choo_m]
set_property IOSTANDARD LVCMOS33 [get_ports choo_m]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {choo_m_IBUF}]


set_property PACKAGE_PIN K3 [get_ports {mode_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[0]}]
set_property PACKAGE_PIN M1 [get_ports {mode_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[1]}]